#####################################################################
# This is Jekyll's configuration file for this project.
#
# For more information, see the documentation:
#
#     https://jekyllrb.com/docs/configuration/
#####################################################################

# Site settings
title: XOXA NYC
description: >-
    XOXA is dedicated to cultivating an inclusive queer community through art, music and performance.
    XOXA curates the best of the Brooklyn underground for femmes and allies.
human_language: en-US # The primary human language you write in.
timezone: America/New_York

main_logo: logo.xoxa.white-on-black.1700x510.png

# Build settings
markdown: kramdown
exclude:
    - vendor
    - README.md

# Blog settings.
paginate: 5    # How many posts per HTML page.
paginate_path: "/blog/page/:num/"
date_format: "%B %e, %Y"
time_format: "%l:%M %p"

# RSS feed settings.
rss:
    items:            10     # How many posts to include in blog RSS/Atom feeds.
    update_period:    weekly # Acceptable values are: `hourly`, `daily`, `weekly`, `monthly`, or `yearly`.
    update_frequency: 1      # How many times in the feed_update_period the feed is updated.
    ttl:              60     # Number of minutes indicating how long to cache the channel content.
    editor_email:     kira@xoxanyc.com      # Email of the person responsible for channel content.
    webmaster_email:  webmaster@example.com # Email of the person responsible for technical issues.
    image:            example-rss-image.png # Image for the RSS feed, if different from the main_logo.


# Collections.
#
# Collections are a Jekyll feature that takes structured data and can
# render a page for each item in that data structure. For example, you
# can make a collection of baking recipes and then, for each recipe in
# the collection, you can make a page with its own Web address to show
# the recipe on your Web site.
collections:
    events:
        output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

iCalendar:
    defaults:
        location: "Brooklyn, NY"
        status: CONFIRMED
        image: event-image-placeholder.jpg
